version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  java-webhook-app:
    build: .
    # command: java -jar app.jar # ENTRYPOINT in Dockerfile handles this
    ports:
      - "8000:8000"
    environment:
      # Pass environment variables from host's .env file
      STREAM_API_SECRET: "${STREAM_API_SECRET}"
      SPLUNK_HEC_URL: "${SPLUNK_HEC_URL}"
      SPLUNK_HEC_TOKEN: "${SPLUNK_HEC_TOKEN}"
      SPLUNK_HEC_SSL_VERIFY: "${SPLUNK_HEC_SSL_VERIFY}"
      REDIS_HOST: redis # Service name in docker-compose is the hostname
      REDIS_PORT: 6379
      REDIS_DB: 0
      WEBHOOK_QUEUE_NAME: "${WEBHOOK_QUEUE_NAME}"
      DEDUPLICATION_WINDOW_SECONDS: "${DEDUPLICATION_WINDOW_SECONDS}"
    depends_on:
      - redis
    # Ensure the app starts after Redis is ready (optional but good practice for production)
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: