server:
  port: 8000

spring:
  # No 'redis:' block here anymore!

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
    com.example: INFO # Keep your application logs at INFO or DEBUG as needed

app:
  stream:
    api-secret: ${STREAM_API_SECRET:your_stream_api_secret_here}
  splunk:
    hec-url: ${SPLUNK_HEC_URL:https://localhost:8088/services/collector/event}
    hec-token: ${SPLUNK_HEC_TOKEN:your_splunk_hec_token_here}
    hec-ssl-verify: ${SPLUNK_HEC_SSL_VERIFY:false}
  queue:
    name: ${WEBHOOK_QUEUE_NAME:stream_webhooks}
  worker:
    deduplication-window-seconds: ${DEDUPLICATION_WINDOW_SECONDS:300}
    poll-interval-ms: 1000